---
- name: Ansible - start
  hosts: localhost 
  become: yes
  become_user: root

  roles:
  - packages
  - zram
  - usbdrive
  - hifiberry
  - { role: nodered,
      become: yes,
      become_user: pi }
  - mopidy
  - nginx
  - hotspot
  - minidlna
