- name: "install apt-get packages"
  apt: 
    name: [ "curl", "exfat-fuse", "exfat-utils", "ntfs-3g" ]
    state: present
    update_cache: yes

- name: "set mount flag 1"
  replace:
    path: /lib/systemd/system/systemd-udevd.service
    regexp: 'MountFlags=slave'
    replace: 'MountFlags=shared'

- name: "set mount flag 2"
  lineinfile:
    path: /lib/systemd/system/systemd-udevd.service
    line: 'MountFlags=shared'
