---

mopidy_password: ''
mopidy_hostname: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
mopidy_media_dir: '/media'

#mopidy_packages:
#  - upmpdcli

mopidy_pip_packages:
  - mopidy-musicbox-webclient
  - Mopidy-Iris
  - Mopidy-Mobile
  - Mopidy-Mopify
  - Mopidy-WebSettings
  - Mopidy-Jukepi
  - Mopidy-API-Explorer
  - Mopidy-Simple-Webclient
#  - Mopidy-ALSAMixer  

# 'ini_file' module settings for mopidy.conf
mopidy_settings:
  - { section: 'audio', option: 'output', value: 'alsasink' }  
  - { section: 'http', option: 'enabled', value: 'true' }
  - { section: 'http', option: 'hostname', value: '{{ mopidy_hostname }}' }
  - { section: 'http', option: 'port', value: '6680' }
  - { section: 'local', option: 'enabled', value: 'true' }
  - { section: 'local', option: 'media_dir', value: '{{ mopidy_media_dir }}' }
  - { section: 'local', option: 'scan_timeout', value: '1000' }
  - { section: 'local', option: 'scan_flush_threshold', value: '100' }
  - { section: 'local', option: 'scan_follow_symlinks', value: 'true' }
#  - { section: 'file', option: 'enabled', value: 'true' }
#  - { section: 'file', option: 'media_dir', value: '{{ mopidy_media_dir }}' }
  - { section: 'mopify', option: 'enabled', value: 'true' }
  - { section: 'mobile', option: 'enabled', value: 'true' }
  - { section: 'iris', option: 'enabled', value: 'true' }
  - { section: 'iris', option: 'country', value: 'NL' }
  - { section: 'iris', option: 'locale', value: 'nl_NL' }
  - { section: 'softwaremixer', option: 'enabled', value: 'true' }
  - { section: 'mpd', option: 'enabled', value: 'true' }
  - { section: 'mpd', option: 'password', value: '{{ mopidy_password }}' }
  - { section: 'mpd', option: 'hostname', value: '{{ mopidy_hostname }}' }
  - { section: 'mpd', option: 'port', value: '6600' }
  - { section: 'musicbox_webclient', option: 'enabled', value: 'true' }
  - { section: 'musicbox_webclient', option: 'musicbox', value: 'TRUE' }
  - { section: 'musicbox_webclient', option: 'on_track_click', value: 'PLAY_ALL' }
  - { section: 'websettings', option: 'enabled', value: 'true' }
  - { section: 'websettings', option: 'musicbox', value: 'true' }
  - { section: 'websettings', option: 'config_file', value: '/etc/mopidy/mopidy.conf' }
  - { section: 'jukepi', option: 'enabled', value: 'true' }
#  - { section: 'alsamixer', option: 'enabled', value: 'true' }
#  - { section: 'alsamixer', option: 'card', value: '1' }
#  - { section: 'alsamixer', option: 'control', value: 'PCM' }
#  - { section: 'alsamixer', option: 'min_volume', value: '0' }
#  - { section: 'alsamixer', option: 'max_volume ', value: '100' }
#  - { section: 'alsamixer', option: 'volume_scale', value: 'cubic' }
