---

mopidy_password: ''
mopidy_hostname: '0.0.0.0'
mopidy_media_dir: '~'

mopidy_packages:
  - mopidy-musicbox-webclient

# 'ini_file' module settings for mopidy.conf
mopidy_settings:
  - { section: 'mpd', option: 'password', value: '{{ mopidy_password }}' }
  - { section: 'mpd', option: 'hostname', value: '{{ mopidy_hostname }}' }
  - { section: 'musicbox_webclient', option: 'enabled', value: 'true' }
  - { section: 'musicbox_webclient', option: 'musicbox', value: 'TRUE' }
  - { section: 'musicbox_webclient', option: 'on_track_click', value: 'PLAY_ALL' }
