---
- name: check if rules file exists
  stat:
    path: /etc/mopidy/mopidy.conf
  register: stat_result

- include: packages.yaml

- include: packages-debian.yaml
  when: ansible_os_family == 'Debian'

- name: copy mopidy.conf
  copy:
    src: mopidy.conf
    dest: /etc/mopidy/mopidy.conf
  when: stat_result.stat.exists == False

- name: Mopidy conf
  ini_file:
    dest: /etc/mopidy/mopidy.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mopidy_settings }}"
  notify: restart mopidy
  when: stat_result.stat.exists == False

- name: Mopidy service
  service:
    name: mopidy
    state: started
    enabled: yes
